global:
  scrape_interval: 15s
  external_labels:
    monitor: 'cloud-native-monitor'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name:  'api-server'
    scrape_interval: 5s
    static_configs:
      - targets: ['api:8181']
        labels:
          group: 'api'
  - job_name:  'worker'
    scrape_interval: 5s
    static_configs:
      - targets: ['worker:8181']
        labels:
          group: 'worker'