version: "3.1"

services:
  api:
    restart: always
    image: cngo-api
    ports:
      - "8080:8080"
    expose:
      - 8080
    links:
      - "mongo:database"
    environment:
      PORT: 8080
      LOG_FORMAT: json
      NATS_SERVER_URL: nats://nats:4222
      PUBSUB_TOPIC_URL: nats://events.api
      PUBSUB_SUB_URL: nats://events.api?queue=worker
      DOCSTORE_URL: mongo://cloud-native-go/
      MONGO_SERVER_URL: mongodb://admin:admin@database:27017
      JAEGER_URI: http://tempo:14268/api/traces
    logging:
      driver: "fluentd"
    volumes:
      - tmpfiles:/app/tmp
    depends_on:
      - mongo
      - nats
      - fluentbit
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthz/liveness"]
      interval: 30s
      timeout: 20s
      retries: 3

  worker:
    restart: always
    image: cngo-worker
    ports:
      - "8080"
    expose:
      - 8080
    links:
      - "mongo:database"
    environment:
      PORT: 8080
      METRICS_PORT: 8181
      LOG_FORMAT: json
      NATS_SERVER_URL: nats://nats:4222
      PUBSUB_TOPIC_URL: nats://events.api
      PUBSUB_SUB_URL: nats://events.api?queue=worker
      DOCSTORE_URL: mongo://cloud-native-go/
      MONGO_SERVER_URL: mongodb://admin:admin@database:27017
      JAEGER_URI: http://tempo:14268/api/traces
    logging:
      driver: "fluentd"
    volumes:
      - tmpfiles:/app/tmp
    depends_on:
      - mongo
      - nats
      - fluentbit
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthz/liveness"]
      interval: 30s
      timeout: 20s
      retries: 3

  # minio:
  #   image: quay.io/minio/minio:RELEASE.2021-11-05T09-16-26Z
  #   command: server /data --console-address ":9001"
  #   ports:
  #     - "9000:9000"
  #     - "9001:9001"
  #   expose:
  #     - "9000"
  #     - "9001"
  #   environment:
  #     MINIO_ROOT_USER: admin
  #     MINIO_ROOT_PASSWORD: password

  nats:
    image: nats:alpine
    restart: always
    ports:
      - "4222"

  fluentbit:
    image: fluent/fluent-bit:1.7
    restart: always
    expose:
      - 24224
    ports:
      - "24224:24224"
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./fluent-bit-parsers.conf:/fluent-bit/etc/fluent-bit-parsers.conf
      - ./tmp/logs:/logs
    depends_on:
      - loki

  loki:
    image: grafana/loki
    restart: always
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  mongo:
    image: mongo
    restart: always
    expose:
      - "27017"
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

  tempo:
    image: grafana/tempo:latest
    ports:
      - "14268:14268"  # jaeger ingest
    volumes:
      - ./tempo-local.yaml:/etc/tempo-local.yaml
    command: -config.file=/etc/tempo-local.yaml

  tempo-query:
    image: grafana/tempo-query:latest
    volumes:
      - ./tempo-query.yaml:/etc/tempo-query.yaml
    ports:
      - "16686:16686"
    command: --grpc-storage-plugin.configuration-file=/etc/tempo-query.yaml

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9292:9090"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3002:3000"

volumes:
  tmpfiles:
